apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rpc-balancer.fullname" . }}-config
  labels:
    {{- include "rpc-balancer.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.config | b64enc }}
---